apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: multytools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multytools
  template:
    metadata:
      labels:
        app: multytools
    spec:
      containers:
      - name: multytools
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "8080"
          - name: HTTPS_PORT
            value: "11443"
        ports:
          - name: http-port
            containerPort: 8080
          - name: https-ports
            containerPort: 11443
---
apiVersion: v1
kind: Service
metadata:
  name: network-multitool
spec:
  selector:
    app: multytools
  ports:
    - name: multitool
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP