apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-deployment
  labels:
    app: nginx_multy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx_multy
  template:
    metadata:
      labels:
        app: nginx_multy
    spec:
      containers:
      - name: multytools
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: 1180
          - name: HTTPS_PORT
            value: 11443
        ports:
        - containerPort: 1180
          name: http_port
        - containerPort: 11443
          name: https_ports
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
