apiVersion: v1
kind: Service
metadata:
  name: network-multitool
spec:
  selector:
    app: nginx_multy
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPort: 80
    - name: multitool
      protocol: TCP
      port: 1180
      targetPort: 1180