apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology
  labels:
    app: multitool
spec:
  selector:
    matchLabels:
      name: multitool
  template:
    metadata:
      labels:
        name: multitool
    spec:
      containers:
      - name: multy
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "8080"
          - name: HTTPS_PORT
            value: "11443"
        ports:
          - name: http-port
            containerPort: 8080
          - name: https-ports
            containerPort: 11443
        volumeMounts:
        - name: nfs-pvc
          mountPath: /nfs
      volumes:
      - name: nfs-pvc
        persistentVolumeClaim:
          claimName: netology-pvc