apiVersion: v1
kind: PersistentVolume
metadata:
  name: netology-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWrite
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
  