apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netology-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "microk8s-hostpath"
  resources:
    requests:
      storage: 1Gi