apiVersion: v1
kind: Service
metadata:
  name: network-multitool
spec:
  selector:
    app: nginx_multy
  ports:
    - name: nginx-port
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multitool
      protocol: TCP
      port: 9002
      targetPort: 8080
  type: ClusterIP