apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-deployment
  labels:
    app: nginx_multy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx_multy
  template:
    metadata:
      labels:
        app: nginx_multy
    spec:
      containers:
      - name: multytools
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "8080"
          - name: HTTPS_PORT
            value: "11443"
        ports:
          - name: http-port
            containerPort: 8080
          - name: https-ports
            containerPort: 11443
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
