apiVersion: v1
kind: Service
metadata:
  name: network-multitool
spec:
  selector:
    app: nginx_multy
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPort: 9001
    - name: multitool
      protocol: TCP
      port: 8080
      targetPort: 9002
  type: ClusterIP