apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: starky_role_binding
subjects:
- kind: User
  name: starky
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: starky-role
  apiGroup: rbac.authorization.k8s.io