apiVersion: v1
kind: Pod
metadata:
  name: echoserver
  labels:
    app.kubernetes.io/name: echoserver
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
    - containerPort: 8080
      name: http-web-svc
  restartPolicy: OnFailure